### ISSUE TITLE
请问这个报错怎么解决的

### ISSUE THREAD

**Issue by Everyer** [HelTi/webpack-M-pages#4]
Error: Cannot find module './config/entrys'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\孙岩\Desktop\webpack-M-pages-webpack3\webpack-M-pages-webpack3\webpack.config.js:8:21)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at requireConfig (C:\Users\孙岩\Desktop\webpack-M-pages-webpack3\webpack-M-pages-webpack3\node_modules\webpack\bin\convert-argv.js:97:18)
    at C:\Users\孙岩\Desktop\webpack-M-pages-webpack3\webpack-M-pages-webpack3\node_modules\webpack\bin\convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\孙岩\Desktop\webpack-M-pages-webpack3\webpack-M-pages-webpack3\node_modules\webpack\bin\convert-argv.js:102:15)

**Comment by HelTi** [comment]
@Everyer  你先运行node output
看错误信息： Cannot find module './config/entrys'。没有生成这个文件。等哪天我改成直接在webpack中运行。先手动生成配置文件下

**Comment by Everyer** [comment]
谢谢哈，不过还有个问题，新手不懂见谅。
1.页面运行是正常了，但是会报错呢，这个怎么解决啊。（报错如下）
ERROR in static/js/pageA595bb1a6b6519799cfb8.js from UglifyJs
Unexpected token: name (urlParts) [static/js/pageA595bb1a6b6519799cfb8.js:377,4]

ERROR in static/js/pageC595bb1a6b6519799cfb8.js from UglifyJs
Unexpected token: name (urlParts) [static/js/pageC595bb1a6b6519799cfb8.js:58,4]

ERROR in static/js/pageB595bb1a6b6519799cfb8.js from UglifyJs
Unexpected token: name (urlParts) [static/js/pageB595bb1a6b6519799cfb8.js:58,4]

ERROR in static/js/testm595bb1a6b6519799cfb8.js from UglifyJs
Unexpected token: name (urlParts) [static/js/testm595bb1a6b6519799cfb8.js:442,4]

ERROR in static/js/index595bb1a6b6519799cfb8.js from UglifyJs
Unexpected token: name (urlParts) [static/js/index595bb1a6b6519799cfb8.js:352,4]
2.每次都clone下来都得手动npm install --save-dev webpack-dev-server

**Comment by zilan830** [comment]
同问这个问题，这个报错是啥意思啊

**Comment by autumnup** [comment]
同问 这个问题请问要怎么解决呢 找了好多资料说是因为es6转es5语法问题 未引入相关模块 试了好久都没有解决

**Comment by HelTi** [comment]
@autumnup @zilan830 @Everyer 大多数是依赖的问题，我这边重新删除node_modules，用cnpm安装后是正常运行，并且正常打包的

**Comment by autumnup** [comment]
我刚刚试了一下 把node_modules删除之后 再重新安装依赖 发现还是报同样的错

**Comment by HelTi** [comment]
@autumnup  你切换到webpack3分支吧，主分支因为某些问题引入路径有问题。master分支不在更新

**Comment by autumnup** [comment]
还是报同样的错

**Comment by HelTi** [comment]
@autumnup  具体的应该是写的js代码问题，把js删了自己写几个看看吧。应该不影响使用

**Comment by autumnup** [comment]
之前有一次我跑起来过 不晓得为什么现在跑不起来了

**Comment by HelTi** [comment]
@autumnup  。。。这，你最好参照代码，自己模仿着写，出错的原因也不具体的

**Comment by HelTi** [comment]
@autumnup 已经修复了

**Comment by HelTi** [comment]
全部换成es6加载模块了

**Comment by HelTi** [comment]
@Everyer
